# Generated by Django 4.2.5 on 2023-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('topic', models.CharField(max_length=122)),
                ('catagory', models.CharField(max_length=122)),
                ('body', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
