# Generated by Django 4.2.5 on 2023-10-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_forum_alter_credentials_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='catagory',
            new_name='category',
        ),
    ]
