# Generated by Django 4.2.5 on 2023-10-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_forum_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='username',
        ),
    ]
