# Generated by Django 4.2.5 on 2023-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_forum_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='mail',
            field=models.CharField(default='randomail@gmail.com', max_length=100),
        ),
    ]
