# Generated by Django 4.2.5 on 2023-10-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_forum_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
