# Generated by Django 4.2.5 on 2023-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='priv',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
