# Generated by Django 4.2.5 on 2023-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='disp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
